SELECT * FROM customer limit(10);
-- Q1. Whta is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue 
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(avg(review_rating:: numeric),2) as "Average Product Rating"
From customer 
group by item_purchased
order by avg(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts Between standard and Express shipping.
SELECT shipping_type, 
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
Group by shipping_type;

--Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers
select subscription_status, COUNT(customer_id) AS total_customers, ROUND(AVG(purchase_amount),2) AS average_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
from customer group by subscription_status
order by total_revenue, average_spend DESC;

--Q6. Which 5 products have the highest percentage with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS diScount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,and show the count of each segment.
with customer_type as ( select customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 then 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
else 'Loyal'
end as customer_segment
from customer)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, 
item_purchased,
COUNT(customer_id) as total_orders ,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased )

select item_rank, category, item_purchased, total_orders
from item_counts
WHERE item_rank <= 3 ;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribs?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
WHERE previous_purchases> 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) AS total_revenue 
from customer
group by age_group
order by total_revenue DESC;
